### PR TITLE
add all downstreams to jenkins build scripts

### PR DESCRIPTION
**Pull request by akva2**
fsi couple us to navier-stokes and its dependencies

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by kmokstad** [comment]
Not sure here if I follow. Is it right to call Stokes, NavierStokes and AdvectionDiffusion downstream of Elasticity? I thought downstream modules are those that depend on the upstream to be built and run. But these modules have no such dependencies to my knowledge (only FSI has). They have in common that they are used by FSI, yes (at least Stokes+NavierStokes). But that is more on a parallel level.

Or what am I missing..

**Comment by akva2** [comment]
There is no side streams. To build fsi all its additional deps will be considered downstreams. It's a limitation of the scripts i cba to complicate just to avoid some test executions

-------- Opprinnelig melding --------
Fra: kmokstad <notifications@github.com>
Dato: 16.03.2017 22:50 (GMT+01:00)
Til: OPM/IFEM-Elasticity <IFEM-Elasticity@noreply.github.com>
Ko: Arne Morten Kvarving <Arne.Morten.Kvarving@sintef.no>, State change <state_change@noreply.github.com>
Emne: Re: [OPM/IFEM-Elasticity] add all downstreams to jenkins build scripts (#16)


Not sure here if I follow. Is it right to call Stokes, NavierStokes and AdvectionDiffusion downstream of Elasticity? I thought downstream modules are those that depend on the upstream to be built and run. But these modules have no such dependencies to my knowledge (only FSI has). They have in common that they are used by FSI, yes (at least Stokes+NavierStokes). But that is more on a parallel level.

Or what am I missing..

**Comment by kmokstad** [comment]
OK, I see, some limitation in the system. But AdvectionDiffusion then? Neither FSI nor Elasticity depends on that one, only NavierStokes do.

**Comment by akva2** [comment]
And fsi depends on nstokes. I would have to separate out the boussineq bit to avoid it.

-------- Opprinnelig melding --------
Fra: kmokstad <notifications@github.com>
Dato: 17.03.2017 00:24 (GMT+01:00)
Til: OPM/IFEM-Elasticity <IFEM-Elasticity@noreply.github.com>
Ko: Arne Morten Kvarving <Arne.Morten.Kvarving@sintef.no>, State change <state_change@noreply.github.com>
Emne: Re: [OPM/IFEM-Elasticity] add all downstreams to jenkins build scripts (#16)


OK, I see, some limitation in the system. But AdvectionDiffusion then? Neither FSI nor Elasticity depends on that one, only NavierStokes do.

**Pull request merged**
